### ISSUE TITLE
Post requests fail since last commit

### ISSUE THREAD

**Issue by kewlfft** [wanth1997/python-ftx#5]
with commit 2b087bcc72ef739d9153cad80dde2bea721670bb, when I am trying to do a withdrawal I am getting the error:

> [ERROR] Request failed!
> {"success":false,"error":"Not logged in: Invalid signature"}

reverting to previous version fixes the issue. I haven't investigated further nor tried other functions but I can do in the coming hours or days.

**Comment by kewlfft** [comment]
after a few checks, replacing `params=params` by `json=params` fixes the issue
https://github.com/wanth1997/python-ftx/blob/2b087bcc72ef739d9153cad80dde2bea721670bb/ftx/client.py#L85

**Comment by wanth1997** [comment]
Thanks for reporting, will fix ASAP

**Comment by kewlfft** [comment]
I use *python-ftx* in a production & test environments, a new release would be appreciate so that I can test future git developments in my test environment and use current state for prod. thanks!

**Comment by wanth1997** [comment]
Fixed! Thanks for reporting and it's my pleasure to help.
Let's make this repo better

commit: fb3462529771c568e863e2e95f73c0efd88a1e3a
