### ISSUE TITLE
this lib missed  some function

### ISSUE THREAD

**Issue by CuongITL** [wanth1997/python-ftx#7]
this module don't have some function like this:

Please add to 'client.py':

```
    def get_open_orders(self) -> Dict:
        return self._get("/orders")
    def get_leverage_tokens(self) -> Dict:
        return self._get("/lt/tokens")
    def get_history_orders(self) -> Dict:
        return self._get("/orders/history")
```

**Comment by wanth1997** [comment]
Thank you for pointing this out!
Will add these functions soon.
And as you can see, you can use self._get("<endpoint>") as walk around.

Enjoy trading.
